### ISSUE TITLE
X axis doesn't start at first datapoint, and doesn't end at last datapoint. 

### ISSUE THREAD

**Issue by decent-developer** [d2bjs/d2b#12]
I am using vue-d2b and I have a weird empty space before and after my graph. This is what it looks like: https://gyazo.com/6ba59e344403edafe5a7eada070e8647.

I know this is probably a configuration issue but I can't figure out what I need to configure from the documentation that is available.

Please help.

**Comment by kevinwarne** [comment]
Hi there! I can certainly help with this. The reason this is occurring is that you are using string values for the x positions. What d2b does is interpret these as generic strings and then uses a [d3.bandScale](https://github.com/d3/d3-scale#band-scales) to find discrete break points for the x values. This in turn adds bandwidth padding on either end of the x-axis. Luckily the x-axis is very easy to customize with the d2b API and configuration power from d3. 

Here is a fiddle of what you are trying to achieve: https://jsfiddle.net/g7bxzsrb/4/

The important parts for this example are in the axisChartConfig data attribute (callback). I'll go over the different parts of that configuration here so that they are more clear. Mostly it just involves using d3 configurations and overriding basic d2b defaults.

```javascript 
// In this callback, we can configure the d2b axis chart generator.
axisChartConfig: function (chart) {

  chart
    // first configure the x axis, the second argument passed to this callback is an 
    // array of x-values that will be used in the chart (e.g. December 1, December 2, December 3, ..)
    .x(function (d, values) {

      return {
        // axis configuration: format the axis tick values with an abbreviated month and day
        // also make sure that there is an axis tick for every (1) day
        axis: d3.axisBottom().tickFormat(d3.timeFormat("%b %d")).ticks(d3.timeDay.every(1)),

        // scale configuration: use the d3 time scale and set the domain (e.g. [min, max]) to
        // the extent of the x values provided to this callback
        scale: d3.scaleTime().domain(d3.extent(values))
      };
    })
    // In addition to configuring the x axis it might also be helpful to configure the tooltip
    .tooltipConfig(function (t) {

      // configure the tooltip title, this callback is given the data values to be rendered 
      // on the currently displayed tooltip
      t.title(function (values) {

        // simply return the properly formatted "x" date for the first value
        return d3.timeFormat("%B %d, %Y")(values[0].x);
      });
    });  
}
```

The only other important thing in the fiddle is that I am using javascript `Date` instances for the x-values rather than strings:
```javascript
[
  {x: new Date('12/1/17'), y: 25},
  {x: new Date('12/2/17'), y: 38},
  {x: new Date('12/3/17'), y: 24},
  ...
]
```

There are other ways to accomplish this. But I consider this way to be best because it uses powerful functionality that d3 has to offer. If you have any further questions don't hesitate to ask!

**Comment by kevinwarne** [comment]
Any luck getting this to work? Let me know if you need any more help resolving this issue.

**Comment by decent-developer** [comment]
Hey, sorry about leaving issue open. I've been too busy to implement but it looks like you know what went wrong, and the fix should work. 

Thanks for the help 👍

**Comment by jondavidjohn** [comment]
Running into this as well, could we get an example on how to do this for arbitrary (categorical) strings on the x axis?  Not necessarily dates specifically?

Thanks!

**Comment by HJK181** [comment]
Hi @kevinwarne,

I used your example to create a chartAxis where I want to stack the data points. Unfortunately the stack are not displayed when formating the X-Axis like you described in your example. When using the .x function from the docs `axis.x({linearPadding: [-0.1, 0.1]});` stacking is working as expected. 

I'm not that familar yet with all that d3 stuff, but I assume I need to add some kind of padding to enable stacking when formating the x axis in daily timeformat. 

Can you give me a hint?

**Comment by kevinwarne** [comment]
Hmm, yeah linearPadding only really works on linear scales (not time scales). One solution might be to just add an extra date to either side of the date domain. Here is the modified fiddle for this: https://jsfiddle.net/31es6ypb/

**Comment by kevinwarne** [comment]
Another option might be to use a d3 band scale. Here is a fiddle https://jsfiddle.net/31es6ypb/2/

Since the example is just working with a few dates, a band scale might make sense. But if you have a large number of discrete x points a time scale makes more sense and will play nicer.

**Comment by HJK181** [comment]
Hi @kevinwarne,

thank you very much for providing those solution. Meanwhile I manged to solve it with a time day offset like so: ` scale: d3.scaleUtc().domain([d3.timeDay.offset(d3.min(points), -1), d3.timeDay.offset(d3.max(points), + 1)])`

But your solutions also look good 👍

**Comment by kevinwarne** [comment]
@HJK181 looks good, nice work!

**Comment by HJK181** [comment]
Hi @kevinwarne, sry for abusing Github as a platform for questions, but I don't know a other way to get support :)

Can you give me a hint for a last issue I'm not sure how to solve? I'm displaying data for 
- 7 days
- 1 month
- one quarter

in my axis chart, were I have timestamps for every day in my axis chart datum. When displaying 7 days everything fits fine into the chart with `axis: d3.axisBottom().tickFormat(d3.timeFormat("%b %d")).ticks(d3.utcDay.every(1)),`

but: when I select 1 quarter, there are to many data points when displaying every single day. Is it the correct solution to change the x axis to display not every day or would groping of timestamps into weekly buckets be the correct solution?

If grouping is the right answer, could you please provide an example as I don't understand the grouping stuff from reading the docs.

Thx.

**Comment by kevinwarne** [comment]
Hi there @HJK181,

I don't think using d2b groups is the answer here. Groups is to add multiple graph sets together so that they may all have the same color / legend indicator.

I would dynamically change the d3.utcDay.every(1) to something else when you get too many data points. You should be able to just update this to d3.utcDay.every(7) and then rerender the chart. 

The other option is like you say, not using a timescale on the axis and instead just group the dates on your own into aggregate bins and then display custom xvalues. Like "week 1", "week 2", ..

Hope this helps,
Kevin

**Comment by HJK181** [comment]
Hi @kevinwarne,

that's exactly the solution I came up as well. Everything is working fine in Chrome, but I have a little problem in Firefox. I want to format the y axis as percentage like in the Fiddle https://jsfiddle.net/zwo3rdmn/1/ In Chrome everything looks good, but in Firefox the tooltip get's placed on the wrong bar. Is this a bug? For me it looks like the tooltip is miss placed as many pixels as the text of the y axis, that's why I added some 'aaaa*' characters in my Fiddle.

Even without the formatted y axis it looks like the tooltip is triggered way before hovering a bar when pointing the mouse on the left hand side of the bar.

Btw. great work, especially with the update documentation. All the added examples are great.

**Comment by kevinwarne** [comment]
@HJK181 this has been fixed in more recent versions of d2b and vue-d2b here is a working fiddle with the versions updated: https://jsfiddle.net/d0rLz7y1/1/

**Comment by HJK181** [comment]
That's awesome, thank you very much for your support.

**Comment by kevinwarne** [comment]
No problem 👍
